description: "This is a template configuration file for the QXMT framework."

global_settings:
  random_seed: &global_seed 42
  model_type: "qkernel"
  task_type: "classification"

dataset:
  generate:
    generate_method: "linear"
    params: {
      "n_samples": 1000,
      "n_features": 784,
      "n_classes": 10,
    }
  split:
    train_ratio: 0.4
    validation_ratio: 0.3
    test_ratio: 0.3
    shuffle: true
  features: null
  raw_preprocess_logic:
    module_name: "qxmt.datasets.raw_preprocess.sampling"
    implement_name: "sampling_by_each_class"
    params:
      n_samples: 200
      labels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      random_seed: *global_seed
  transform_logic: 
    module_name: "qxmt.datasets.transform.reducer"
    implement_name: "dimension_reduction_by_pca"
    params:
      n_components: 80
      random_seed: *global_seed
      normalize: true

device:
  platform: "pennylane"
  device_name: "lightning.qubit"
  n_qubits: 10
  shots: null

feature_map:
  module_name: "astronaut.seed.quantum_kernel.feature_map"
  implement_name: "SeedFeatureMap"
  params: {}

kernel:
  module_name: "qxmt.kernels.pennylane"
  implement_name: "FidelityKernel"
  params: {}

model:
  name: "qsvc"
  params:
    C: 1.0
    gamma:  "scale"

evaluation:
  default_metrics:
  - "accuracy"
  - "precision"
  - "recall"
  - "f1_score"
  custom_metrics: []
